Vídụ3.3.2.2

In [1]:
import numpy as np 
B=np.array([[1,2,3],[4,5,6],[7,8,9]]) 
B[1,2]  

np.int64(6)

In [2]:
B[0,0]=0                #Chỉnh sửa giá trị ở dòng 0, cột 0 thành 0 
np.array(B)

array([[0, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Ví dụ 3.3.2.3. Mảng con một chiều

In [ ]:
import numpy as np 
A=np.arange(10) 
A 


array([4, 5, 6])

In [ ]:
A[:5]  

In [ ]:
A[4:7] 

Ví dụ 3.3.2.4. Mảng con đa chiều

In [7]:
import numpy as np 
B=np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]]) 
B 

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 0, 1, 2]])

In [ ]:
B[:2,:3]   

In [ ]:
B[:3,::2] 

In [ ]:
B[ ::-1, ::-1] 

Ví dụ 3.3.2.5.

In [8]:
arr=np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]]) 
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
print("Cột đầu tiên của mảng arr là: ",arr[:,0])    
print("Hàng đầu tiên của mảng arr là:",arr[0,:]) 
print("Hàng đầu tiên của mảng arr là:",arr[0])

Cột đầu tiên của mảng arr là:  [1 4 7]
Hàng đầu tiên của mảng arr là: [1 2 3]
Hàng đầu tiên của mảng arr là: [1 2 3]


Ví dụ 3.3.3.1

In [ ]:
import numpy as np 
 
# Tạo mảng 2 chiều 3x3 
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]]) 
 
# Lấy view mới chỉ chứa 2 dòng và 2 cột của mảng gốc 
arr_view = arr_2d[:2, :2].view() 
print(arr_view)   #in mảng con arr_con vừa được slicing từ hàm view 

In [ ]:
# Thay đổi giá trị trong view 
arr_view[0, 0] = 100 #Chỉnh sửa phần tử ở dòng 0, cột 0 thành 10. 
print(arr_view) 

In [ ]:
print("Mảng gốc sau khi thay đổi giá trị trong view:") 
print(arr_2d)

Vídụ3.3.3.2.Giảsửtacómảngarrbanđầu(xemVídụ3.3.3.1:)

In [10]:
sub_arr=arr[:2,:2] #slicing mảng con lấy 2 dòng, 2 cột của mảng arr 
print(sub_arr)  

[[1 2]
 [4 5]]


In [ ]:
sub_arr[0,0]=10  #Chỉnh sửa phần tử ở dòng 0, cột 0 của mảng con thành 10. 
print(sub_arr)  

In [ ]:
print(arr) 

 Vídụ3.3.3.3.Xétmảngbanđầu(XemOut[37]),ởvídụ3.3.2.5

In [12]:
sub_arr_copy=arr[:2,:2].copy()  #Thêm phương thức copy(). 
print(sub_arr_copy)  

[[1 2]
 [4 5]]


In [ ]:
sub_arr_copy[0,0]=10    #sửa phần tử ở dòng 0, cột 0 của mảng                
 # copy thành 10. 
print(sub_arr_copy) 

[[10  2]
 [ 4  5]]


In [14]:
print(arr) 

[[1 2 3]
 [4 5 6]
 [7 8 9]]


 Vídụ3.3.3.4.

In [16]:
arr=np.arange(1,10)            #Tạo mảng một chiều arr có 9 phần tử từ 1-9 
grid= arr.reshape((3,3))#chuyển đổi mảng arr thành mảng grid, 3x3 
grid 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Vídụ3.3.3.5.Tạomộtmatrậnhàng(rowvector)từmảngmộtchiều

In [17]:
x = np.array([1, 2, 3]) 
x.reshape((1, 3)) #tạo ma trận hàng thông qua reshape.

array([[1, 2, 3]])

In [ ]:
x[np.newaxis, :]

In [ ]:
x.reshape((3, 1))

In [ ]:
x[:,np.newaxis]

Vídụ3.3.4.1

In [ ]:
x = np.array([1, 2, 3]) 
y = np.array([4, 5, 6]) 
np.concatenate([x,y]) #Kết hợp ma trận x, y 

Hàmconcatenate()cũngcóthểsửdụngchocácmảnghaichiều:

In [15]:
import numpy as np 
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng 
c = np.concatenate((a, b))  
print(result) 

NameError: name 'result' is not defined

In [ ]:
# Kết hợp  theo chiều thứ hai (trục ngang/trục 1) của mảng,  trục được đánh chỉ số từ 0. 
d = np.concatenate([a, b], axis=1) 
print(d)

Vídụ3.3.4.2

In [ ]:
import numpy as np 
a = np.array([[1, 2], 
              [3, 4]]) 
b = np.array([[5, 6], 
              [7, 8]]) 
# Kết hợp theo chiều đầu tiên (trục dọc/ trục 0) của mảng 
c = np.vstack((a, b))  
 
# Kết hợp theo chiều ngang (trục ngang/ trục 1) của mảng 
d = np.hstack((a,b)) 
print(c) 
print(d) 

Ví dụ 3.3.4.3

In [ ]:
import numpy as np 
arr = np.arange(10)   #Tạo mảng arr gồm 10 phần tử từ 0-9 
sub_arr1=np.split(arr,[3, 6]) #chia mảng arr theo chỉ mục [3, 6]  
#Phần đầu tiên bắt đầu từ chỉ mục 0 và kết thúc trước chỉ mục 3. 
#Phần thứ hai bắt đầu từ chỉ mục 3 và kết thúc trước chỉ mục 6. 
 
sub_arr2=np.split(arr,2) #chia mảng arr thành 2 phần bằng nhau  
print("Mảng con sub_arr1 là:", sub_arr1, "\n") 
print("Mảng con sub_arr2 là:", sub_arr2) 

Vídụ3.3.4.4

In [ ]:
import numpy as np 
arr = np.arange(16).reshape((4,4)) 
arr 

In [ ]:
upper,lower = np.vsplit(arr,2) #Tách theo trục ngang 
print("Kết quả sau khi tách từ mảng ban đầu \n") 
print(upper,"\n") 
print(lower,"\n") 

In [ ]:
left,right=np.hsplit(arr,2)   #Tách theo trục dọc 
print("Kết quả sau khi tách từ mảng ban đầu \n") 
print(left,"\n") 
print(right,"\n")

Vídụ3.3.5.1.

In [18]:
import numpy as np 
 
arr=np.array([1,2,3]) 
new_arr=np.append(arr,4) 
 
print(arr) 
print(new_arr)

[1 2 3]
[1 2 3 4]


Vídụ3.3.5.2: Thêm phần tử vào vị trí cụ thể trong mảng 1 chiều:

In [ ]:
#Thêm phần tử vào vị trí cụ thể trong mảng 1 chiều: 
 
arr = np.array([1, 2, 3, 4, 5]) 
new_element = 10 
index_to_insert = 2 
 
new_arr = np.insert(arr, index_to_insert, new_element) 
 
print(new_arr)

In [ ]:
#Thêm phần tử vào vị trí cụ thể trong mảng 2 chiều: 
arr_2d = np.array([[1, 2], [3, 4], [5, 6]]) 
new_element = [7, 8] 
row_to_insert = 1 
 
new_arr_2d=np.insert(arr_2d,row_to_insert,new_element,axis=0) 
print(new_arr_2d)

 Vídụ3.3.6.1.Tìmphầntửcógiátrịxtrongmộtmảngnumpy

In [ ]:
#Tìm chỉ mục (vị trí) phần tử trong mảng 1 chiều: 
 
arr = np.array([1, 2, 3, 4, 5]) 
indices = np.where(arr==3) 
indices

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) 
indices = np.argwhere(arr==3) 
indices 

 Vídụ3.3.6.3

In [ ]:
arr = np.array([1, 5, 2, 3, 4]) 
max_idx = np.argmax(arr) 
min_idx = np.argmin(arr) 
 
print(max_idx) 
print(min_idx)

 Vídụ3.3.6.4.

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) 
sorted_arr = np.sort(arr) 
 
sorted_arr 

In [ ]:
arr = np.array([1, 2, 3, 4, 5]) 
arr.sort() 
 
arr 

Sửdụnghàmnumpy,np.sort()vàđảongượcmảng:

In [ ]:
arr = np.array([3, 1, 4, 2, 5]) 
sorted_arr_descending= np.sort(arr)[::-1] 
 
sorted_arr_descending 

Sửdụngphươngthứcsort()củamảngvàđảongượcmảng

In [ ]:
arr = np.array([3, 1, 4, 2, 5]) 
arr.sort()                   
 
arr[::-1] 

3.3.7. Xóa mảng Numpy

Vídụ3.3.7.1.

In [ ]:
#Xóa một phần tử ở vị trí trong mảng 
arr = np.array([3, 1, 4, 2, 5]) 
idx_to_delete = 2                 #Xóa phần tử 4 ở chỉ mục 2. 
new_arr=np.delete(arr,idx_to_delete) 
 
new_arr

In [ ]:
#Xóa nhiểu phần tử trong mảng 
arr = np.array([3, 1, 4, 2, 5]) 
idx_to_delete = [1, 3] 
new_arr = np.delete(arr, idx_to_delete) 
 
new_arr

In [ ]:
#Xóa phần tử trên mảng 2 chiều 
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]) 
row_idx_to_delete = 1 
 
new_arr_2d = np.delete(arr_2d, row_idx_to_delete, axis=0)

Vídụ3.3.7.2.

In [20]:
arr = np.array([1, 2, 3, 4, 5]) 
del arr 
arr 

NameError: name 'arr' is not defined

Vídụ3.3.7.3.

In [21]:
arr = np.array([1, 2, 3, 4, 5]) 
arr = None  
print(arr) 

None


Ví dụ 3.3.8.1. 

In [22]:
import numpy as np 
 
# Định nghĩa kiểu dữ liệu cho một Structured Array 
dtype = [('name', 'U20'), ('age', int), ('height', float)] 
 
# Tạo một Structured Array 
data = np.array([('Minh', 22, 181.3), 
                 ('Lan', 40, 160.6), 
                 ('Linh', 31, 163.2), 
                 ('Lương',18,175.5), 
                 ('Thanh',50, 165.0)], dtype=dtype) 
 
print(data) 
 
print(data.dtype)

[('Minh', 22, 181.3) ('Lan', 40, 160.6) ('Linh', 31, 163.2)
 ('Lương', 18, 175.5) ('Thanh', 50, 165. )]
[('name', '<U20'), ('age', '<i8'), ('height', '<f8')]
