Để cài đặt NumPy trước hết cần phải cài đặt Python(xem Tin học cơ sở). Yêu cầu >=3.10
 Trong tài liệu này chúng ta giới thiệu một số cách cài đặt NumPy trong VS Code.
 b. Cài đặt
 Cách 1: Sử dụng Anaconda (xem phụ lục kèm theo), nó bao gồm Python, NumPy và các thư
 viện phổ biến được sử dụng khác cho tính toán khoa học và xử lý dữ liệu.
 Cách 2: cài NumPy như một package Python bình thường, chúng ta có thể cài từ terminal hoặc
 powershell, qua Pip bằng câu lệnh:
 python –m pip  install –upgrade pip
 python –m pip install numpy
 Nâng cấp pip để đảm bảo công cụ quản lý gói 
hoạt động tốt.
 Cài đặt NumPy vào đúng môi trường Python.
 Mẹo: Có thể cài đặt ngay trong môi trường Jupyter Notebook bằng cách gõ:
 !python –m pip  install –upgrade pip
 !python –m pip install numpy

khai báo so sánh biến số nguyên (cộng tổng từ 1 đến 100)

In [3]:
# Python code 
result = 0 
for i in range(100): 
  result += i; 
print(result)

4950


vd 3.2.2

In [4]:
import numpy as np 
 
#Kiểu dữ liệu nguyên: 
arr_int=np.array([1,2,3,4],dtype=np.int32) 
arr_int.dtype 

dtype('int32')

In [5]:
#Kiểu dữ liệu số thực: 
arr_float = np.array([1.1, 2.2, 3.3], dtype=np.float64) 
arr_float.dtype  # Output: float64 

dtype('float64')

Vídụ.Tạomảngtừdanhsách(list)thôngquatựđộngsuyluậnkiểudữliệu:

In [ ]:
import numpy as np 
 
my_list = [1, 2, 3, 4, 5] 
arr_1 = np.array(my_list) 
print(arr_1) 

Ví dụ.Tạo numpy array từ một bộ (tuple) với kiểu dữ liệu được tự động suy luận

In [ ]:
import numpy as np 
 
my_tuple = (1, 2, 3, 4, 5) 
arr_3 = np.array(my_tuple) 
print(arr_3)

Vídụ3.2.5.4.Tạomảng2chiều

In [ ]:
import numpy as np 
 
arr_4=np.array([(1,2,3), (4,5,6)]) 
print(arr_4)

 1. Hàmnp.zeros()

In [ ]:
import numpy as np 
#Tạo mảng có 5 phần tử là số nguyên nhận giá trị 0 
np.zeros(5,dtype=int) 

2. Hàmones()
Cú pháp: numpy_array = np.ones(n, dtype)
 Trong đó:
 o n: là số lượng phần tử của mảng muốn tạo. Nó có thể là một số nguyên
 hoặc một tuple chứa các số nguyên, tạo thành một mảng có kích thước
 nhiều chiều.
 o dtype: là kiểu dữ liệu của các phần tử trong mảng. Mặc định là float64.
 Ví dụ .
 Tạo mảngđachiều kích thước 3x3 là các số thực có giá trị đều = 1

In [ ]:
import numpy as np 
# Tạo mảng kích thước 3x3 các số thực có giá trị  = 1 
np.ones((3,3),dtype=float) 

3. Hàmfull()

In [1]:
import numpy as np 
# Tạo mảng kích thước 5x5 các số thực có giá trị  = 100 
np.full((5,5),100,dtype=float)

array([[100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.],
       [100., 100., 100., 100., 100.]])

4.Hàmnp.arange()

In [ ]:
import numpy as np 
# Tạo mảng chứa các số từ 0 đến 9 
arr_1 =np.arange(10) 
print(arr_1)

In [ ]:
import numpy as np 
# Tạo mảng chứa các số từ 5 đến 14 với bước nhảy là 2 
arr_2 =np.arange(5, 15, 2) 
print(arr_2) 

In [ ]:
import numpy as np 
# Tạo mảng chứa các số từ 0 đến 1 với bước nhảy là 0.1 và kiểu dữ liệu là float. 
arr_3 =np.arange(0, 1, 0.1, dtype=float) 
print(arr_3)

5. Hàmnumpy.linspace()

In [2]:
import numpy as np 
# Tạo mảng chứa 5 giá trị từ 0 đến 10 (gồm giá trị kết thúc) 
arr_1 = np.linspace(0, 10, 5) 
print(arr_1) 

[ 0.   2.5  5.   7.5 10. ]


In [3]:
# Tạo mảng chứa 10 giá trị từ 0 đến 1 (không chứa giá trị # kết thúc) 
arr_2 = np.linspace(0, 1, 10, endpoint=False) 
print(arr_2) 

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [4]:
# Tạo mảng chứa 100 giá trị từ 1 đến 10 và trả về kích thước bước. 
arr_3, step = np.linspace(1, 10, 100, retstep=True) 
print(arr_3) 
print("Step size:", step) 

[ 1.          1.09090909  1.18181818  1.27272727  1.36363636  1.45454545
  1.54545455  1.63636364  1.72727273  1.81818182  1.90909091  2.
  2.09090909  2.18181818  2.27272727  2.36363636  2.45454545  2.54545455
  2.63636364  2.72727273  2.81818182  2.90909091  3.          3.09090909
  3.18181818  3.27272727  3.36363636  3.45454545  3.54545455  3.63636364
  3.72727273  3.81818182  3.90909091  4.          4.09090909  4.18181818
  4.27272727  4.36363636  4.45454545  4.54545455  4.63636364  4.72727273
  4.81818182  4.90909091  5.          5.09090909  5.18181818  5.27272727
  5.36363636  5.45454545  5.54545455  5.63636364  5.72727273  5.81818182
  5.90909091  6.          6.09090909  6.18181818  6.27272727  6.36363636
  6.45454545  6.54545455  6.63636364  6.72727273  6.81818182  6.90909091
  7.          7.09090909  7.18181818  7.27272727  7.36363636  7.45454545
  7.54545455  7.63636364  7.72727273  7.81818182  7.90909091  8.
  8.09090909  8.18181818  8.27272727  8.36363636  8.45454545  8.545

Vídụ.Sửdụnghàmnumpy.linspace()đểtạomộtmảngcó5phầntửtừ0đến10
 vớikiểudữliệulàfloat.

In [ ]:
import numpy as np 
# Tạo mảng gồm 5 phần tử từ 0 đến 10 với kiểu dữ liệu là float 
arr_4 = np.linspace(0, 10, num=5, dtype=float) 
print(arr_4)  
print(arr_4.dtype) 

6. Hàmnp.random.random()

In [ ]:
import numpy as np 
# Tạo môt mảng 1 chiều gồm 5 giá trị ngẫu nhiên từ phân phối đều 
#trong khoảng từ 0 đến 1 
arr_5 = np.random.random(5) 
print(arr_5) 

7. Hàmnp.random.normal()

In [ ]:
import numpy as np 
# Tạo môt mảng 100 giá trị ngẫu nhiên từ phân phối chuẩn với # 
#trung bình 0 và độ lệch chuẩn là 1. 
arr_6 = np.random.normal(loc=0.0, scale=1.0, size=100) 
print(arr_6)

8. Hàmnp.random.randint()

In [6]:
import numpy as np 
# Tạo mảng 2 chiều 3x3 gồm các số nguyên ngẫu nhiên từ 0 9 
arr_7 = np.random.randint(0,10,(3,3)) 
print(arr_7)  

[[4 3 1]
 [4 4 3]
 [6 2 3]]


9. Hàmnp.eye()

In [ ]:
import numpy as np 
# Tạo mảng 2 chiều 3x3  
np.eye(3,3)

10. Hàmnp.empty()

In [ ]:
import numpy as np 
# Tạo mảng rỗng gồm 5 phần tử, giá trị của 5 phần tử này có thể là bất kỳ giá trị 
# nào đã lưu trong bộ nhớ trước đó. 
np.empty(5) 