Ví dụ 3.4.4.3.

In [1]:
import numpy as np 
arr = np.array([0,1,2]) 
arr 

array([0, 1, 2])

Ví dụ 3.4.4.4.

In [2]:
import numpy as np 
arr1 = np.arange(3) 
arr2=np.arange(3)[:,np.newaxis] 
#np.newaxis sử dụng để cho biết một chiều mới được thêm vào 
print(arr1) 
print(arr2) 

[0 1 2]
[[0]
 [1]
 [2]]


In [3]:
arr1 + arr2 

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

Quitắc1:Nếuhaimảngkhácnhauvềsốchiều,hìnhdạngcủamảngcóítchiều
 hơnsẽđượcbổsungbằngcácgiátrị1ởphíatrước(bêntrái).
Qui tắc2:Nếuhìnhdạngcủa2mảngkhôngkhớpnhauởbấtkỳchiềunào,
 mảngcóhìnhdạngbằng1trongchiềuđósẽđượckéodãnđểkhớpvớihình
 dạngkhác.
Qui tắc3:Nếuởbấtkỳchiềunàokíchthướcđềukhôngkhớpvàcảhaikhông
 bằng1,khiđósẽphátsinhlỗi.

 Vídụ3.4.4.5.Xé phép cộng một mảng 2 chiều với một  mảng 1 chiều sau

In [4]:
import numpy as np 
arr1=np.ones((2,3)) 
arr2 = np.arange(3) 
print(arr1.shape) 
print(arr2.shape)

(2, 3)
(3,)


In [5]:
arr1 + arr2

array([[1., 2., 3.],
       [1., 2., 3.]])

 Ví dụ 3.4.3.3. : tính toán tỷ lệ phần trăm tăng trưởng của dữ liệu trong một tập dữ liệu lớn:

In [ ]:
import numpy as np 
# Tạo mảng dữ liệu với kích thước lớn (1000 phần tử) 
data = np.random.randint(100, 200, size=1000) 
# Tạo một giá trị trung bình (số thực) 
mean_value = np.array([data.mean()]) 
# Tính tỷ lệ phần trăm tăng trưởng bằng cách áp dụng broadcasting 
percentage_growth= (data - mean_value) / mean_value * 100 
# In ra 10 phần tử đầu tiên của mảng dữ liệu và tỷ lệ phần trăm tăng trưởng 
print("Dữ liệu gốc:", data[:10]) 
print("Tỷ lệ phần trăm tăng trưởng:", 
percentage_growth[:10]) 

 Ví dụ 3.5.2. Giảsửcódanhsáchngườitruycậpđịachỉtrangwebuneti.edu.vntrong
 mộttuầngầnnhấtlà

In [7]:
import numpy as np 
visitors = np.array([10200, 9875, 13567,7900,11200, 8871, 12567])

In [8]:
sum = 0 
for i in visitors: 
    if (i>10000): 
        sum+=i 
print(sum) 

47534


Sau đây là cách giải sử dụng Masks 

In [9]:
mask = visitors > 10000 
mask 

array([ True, False,  True, False,  True, False,  True])

In [10]:
#Áp dụng mask để lọc các phần  tử thỏa mãn điều kiện (>10000) 
visitors[mask] 

array([10200, 13567, 11200, 12567])

In [11]:
#Tính tổng mảng các phần tử được lọc ra 
visitors[mask].sum() 

np.int64(47534)

Vídụ.3.5.5.1

In [12]:
import numpy as np 
import numpy.ma as ma 
 
#Tạo một mảng NumPy bình thường 
arr = np.array([1,2,3,4,5,6,7,8,9]) 
# Tạo một mảng mask cho các giá trị không hợp lệ 
mask =arr>6 
masked_arr=np.ma.masked_array(arr,mask) 
 
masked_arr 

masked_array(data=[1, 2, 3, 4, 5, 6, --, --, --],
             mask=[False, False, False, False, False, False,  True,  True,
                    True],
       fill_value=999999)

In [13]:
# Lấy các giá trị hợp lệ từ mảng ban đầu bằng cách sử dụng mảng mask 
valid_values = arr[~mask] 
 
print("Dữ liệu ban đầu:", arr) 
print("Mảng mask:", mask) 
print("Các giá trị hợp lệ từ mảng ban đầu:", valid_values)

Dữ liệu ban đầu: [1 2 3 4 5 6 7 8 9]
Mảng mask: [False False False False False False  True  True  True]
Các giá trị hợp lệ từ mảng ban đầu: [1 2 3 4 5 6]


3.6.2. Chỉ mục kết hợp (Combined Indexing

In [14]:
arr = np.arange(16).reshape(4, 4) 
print("Mảng gốc ban đầu:\n arr = ", arr) 
  
#Lấy các phần tử arr[3, 1], arr[3, 2] và arr[3, 3] 
sub_arr = arr[3, [1, 2, 3]] 
print("Mảng con: sub_arr = ", sub_arr) 

Mảng gốc ban đầu:
 arr =  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
Mảng con: sub_arr =  [13 14 15]
